### ISSUE TITLE
Update v2.1.1

### ISSUE THREAD

**Issue by eric2905** [Newan/ioBroker.bluelink#31]
After Update to v2.1.1 (from v2.1.0) remains as "installable" (update to v2.1.1).

**Comment by Newan** [comment]
please check 2.1.2

**Comment by Jockelflo** [comment]
since 2.1.2 i can not connect with the host

**Comment by Newan** [comment]
Please post a debug log

**Comment by Jockelflo** [comment]
<html>
<body>


2021-11-07 03:23:30.409 - error: host.nuciobroker Caught by controller[0]: internal/modules/cjs/loader.js:303
--
2021-11-07 03:23:30.409 - error: host.nuciobroker Caught by controller[0]: throw err;
2021-11-07 03:23:30.409 - error: host.nuciobroker Caught by controller[0]: ^
2021-11-07 03:23:30.409 - error: host.nuciobroker Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/bluelinky/dist/index.js'. Please verify that the package.json has a valid "main" entry
2021-11-07 03:23:30.409 - error: host.nuciobroker Caught by controller[0]: at tryPackage (internal/modules/cjs/loader.js:295:19)
2021-11-07 03:23:30.409 - error: host.nuciobroker Caught by controller[0]: at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
2021-11-07 03:23:30.409 - error: host.nuciobroker Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
2021-11-07 03:23:30.409 - error: host.nuciobroker Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:887:19)
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.bluelink/main.js:4:19)
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32) {
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: code: 'MODULE_NOT_FOUND',
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: path: '/opt/iobroker/node_modules/bluelinky/package.json',
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: requestPath: 'bluelinky'
2021-11-07 03:23:30.410 - error: host.nuciobroker Caught by controller[0]: }
2021-11-07 03:23:30.410 - error: host.nuciobroker instance system.adapter.bluelink.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-11-07 03:23:30.410 - info: host.nuciobroker Restart adapter system.adapter.bluelink.0 because enabled


</body>
</html>

**Comment by Newan** [comment]
Please reinstall all, there are modules missig

**Comment by Jockelflo** [comment]
Hi,
ich musste manuell zusätzlich zum deinstall auch das vorhandene Verzeichnis löschen. Nun läuft es.
Danke
